apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "load-users.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      name: {{ template "load-users.fullname" . }}
      labels:
        app: {{ template "load-users.fullname" . }}
    spec:
      containers:
      - name: {{ template "load-users.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        args: [
          "--log-level",
          "info",
          "load-users",
          "--akey",
          "{{ .Values.s3.accessKey }}",
          "--skey",
          "{{ .Values.s3.secretKey }}"
        ]
      restartPolicy: Never
