apiVersion: v1
kind: Pod
metadata:
  name: {{ template "fullname" . }}-{{ .Values.pubsub.name }}
  labels:
    app: {{ template "fullname" . }}-{{ .Values.pubsub.name }}
spec:
  containers:
  - name: "{{ .Chart.Name }}-{{ .Values.pubsub.name }}"
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    args: [
      "--log-level",
      "info",
      "start-user-reply"
    ]

