apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "fullname" . }}-users"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-users
    spec:
      containers:
        - name: {{ .Chart.Name }}-users
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [
            "--log-level",
            "{{ .Values.logLevel }}",
            "start-user-server",
            "--dictyuser-pass",
            $(DICTYUSER_PASSWORD),
            "--dictyuser-db",
            $(DICTYUSER_DB),
            "--dictyuser-user", 
            $(DICTYUSER_USER),
            "--user-api-http-host",
            "{{ .Values.apiHost }}",
            "--port",
            "{{ .Values.service.users.port }}"
          ]
          env:
          - name: DICTYUSER_DB
            valueFrom:
              configMapKeyRef:
                name: "{{ .Values.dictyContentPostgres.configMap.name }}"
                key: "{{ .Values.dictyContentPostgres.configMap.database }}"
          - name: DICTYUSER_USER
            valueFrom:
              configMapKeyRef:
                name: "{{ .Values.dictyContentPostgres.configMap.name }}"
                key: "{{ .Values.dictyContentPostgres.configMap.user }}"
          - name: DICTYUSER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.dictyContentPostgres.secrets.name }}"
                key: "{{ .Values.dictyContentPostgres.secrets.password }}"
          ports:
          - name: {{ .Values.service.users.name }}
            containerPort: {{ .Values.service.users.port }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.path }}
              port: {{ .Values.service.users.port }}
            initialDelaySeconds: {{ .Values.healthCheck.initial }}
            timeoutSeconds: 1
            periodSeconds: {{ .Values.healthCheck.period }}
      {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
